Implement new command line parsing in asl_reg and add in options for fieldmap input

diff --git a/asl_reg b/asl_reg
--- a/asl_reg
+++ b/asl_reg
@@ -40,36 +40,65 @@ if [ -z $1 ]; then
    exit 1
 fi
 
+#prase command line
 until [ -z $1 ]; do
-    case $1 in
-	-o) outflag=1 outdir=$2
-	    shift;;
-	-i) inflag=1 infile=$2
-	    shift;;
-	-s) strucflag=1 struc=$2
-	    shift;;
-	-m) mask=$2
-	    shift;;
-#	-t) transflag=1 trans=$2
-#	    shift;;
-	-r) lowstrucflag=1 lowstruc=$2
-	    shift;;
-	--imat) init=1 inmat=$2
-		shift;;
-	--inweight) inweight=$2
-		    shift;;
-	-c) cflag=1 cfile=$2
-	    shift;;
+
+# look at this option and determine if has an argument specified by an =
+option=`echo $1 | sed s/=.*//`
+arg="" #specifies if an argument is to be read from next item on command line (=1 is is when = is used)
+if [ $option = $1 ]; then
+# no argument to this command has been found with it (i.e. after an =)
+# if there is an argument it will be the next option
+    argument=$2
+else
+    arg=1
+    argument=`echo $1 | sed s/.*=//`
+fi
+
+takeargs=0;boolarg="";isbool="";
+    
+    case $options in
+	-o) outflag=1 outdir=$argument
+	    takeargs=1;;
+	-i) inflag=1 infile=$argument
+	    takeargs=1;;
+	-s) strucflag=1 struc=$argument
+	    takeargs=1;;
+	-m) mask=$argument
+	    takeargs=1;;
+	-r) lowstrucflag=1 lowstruc=$argument
+	    takeargs=1;;
+	--imat) init=1 inmat=$argument
+		takeargs=1;;
+	--inweight) inweight=$argument
+		    takeargs=1;;
+	-c) cflag=1 cfile=$argument
+	    takeargs=1;;
 	--sbet) sbet=$2
-		shift;;
-	--tissseg) tissseg=$2
-		   shift;;
-	--finalonly) finalonly=1 #only run the final BBR part
+		takeargs=1;;
+	--tissseg) tissseg=$argument
+		   takeargs=1;;
+	--finalonly) isbool=1;
+		     boolarg=finalonly #only run the final BBR part
 		    ;;
-	--mainonly) mainonly=1 # only run the first flirt part (to get inital alignment)
+	--mainonly) isbool=1;
+		    boolarg=mainonly # only run the first flirt part (to get inital alignment)
 	    ;;
-	--flirtsch) flirtsch=$2
-	    shift;;
+	--flirtsch) flirtsch=$argument
+		    takeargs=1;;
+	--fmap) fmap=$argument
+		takeargs=1;;
+	--fmapmag) fmapmag=$argument
+		   takeargs=1;;
+	--fmapmagbrain) fmapmagbrain=$argument
+			takeargs=1;;
+	--echospacing) echospacing=$argument
+		       takeargs=1;;
+	--pedir) pedir=$argument
+		 takeargs=1;;
+	--nofmapreg) isbool=1
+		     boolarg=nofmapreg
+		     ;;
 	--debug) debug=1
 	    ;;
 	*)  Usage
@@ -77,7 +106,43 @@ until [ -z $1 ]; do
 	    echo ""
 	    exit 1;;
     esac
-    shift
+
+    # sort out a shift required by a command line option that takes arguments
+    if [ -z $arg ]; then
+	# an argument has been supplied on the command NOT using an =
+	if [ $takeargs -eq 1 ]; then
+	    shift;
+	fi
+    fi
+
+     if [ ! -z $isbool ]; then
+	    # this is an (explicit) boolean setting
+	if [ ! -z $arg ]; then
+	    # an argument has been supplied on the command using an =
+	    # set the variable based on the argument
+	    case $argument in
+		on) eval $boolarg=1
+		    ;;
+		off) eval $boolarg=""
+		     ;;
+		1) eval $boolarg=1
+		   ;;
+		0) eval $boolarg=""
+		   ;;
+		*)  Usage
+		    echo "Error! Unrecognised setting for boolean option: $1"
+		    echo ""
+		    exit 1;;
+	    esac
+	else
+	    # no argument has been suppled with this command (NOTE that you cannot supply an arugment to a bool option without an =)
+	    # this sets the variable to true
+	    eval $boolarg=1;
+	fi
+     fi
+     
+     # shift to move on to next parameter
+     shift
 done
 
 echo "ASL_REG"
@@ -191,6 +256,11 @@ echo "Registration FINAL stage (BBR)"
     ${FSLDIR}/bin/imcp $mask $outdir/mask
     
     # do a final refinement of the registration using the perfusion and the white matter segmentation - using epi_reg to get BBR (and allow for fielmap correction in future)
+
+    # Without fieldmap
+    $FSLDIR/bin/epi_reg --epi=$tempdir/asldata_brain --t1=$struc --t1brain=$sbet $epi_inittext --out=$tempdir/low2high_final --wmseg=$tissseg $weigthinstr
+
+    # With fieldmap
     $FSLDIR/bin/epi_reg --epi=$tempdir/asldata_brain --t1=$struc --t1brain=$sbet $epi_inittext --out=$tempdir/low2high_final --wmseg=$tissseg $weigthinstr
     
     #	$FSLDIR/bin/flirt -ref $sbet -in $infile -dof 6 -cost bbr -wmseg $wmseg -init $tempdir/low2high.mat -omat $tempdir/low2high.mat -out $tempdir/low2high_final -schedule ${FSLDIR}/etc/flirtsch/bbr.sch
