Various fixes for the use of fsl_anat results (where oxford_asl previously relied on detection of structural image input). Option to turn off stage 2 of the registration.

diff --git a/oxford_asl b/oxford_asl
--- a/oxford_asl
+++ b/oxford_asl
@@ -147,7 +147,7 @@ if [ ! -z $nativeout ]; then
 fi
 if [ ! -z $structout ]; then
     if [ ! -d  $outdir/struct_space/$subdir ]; then mkdir $outdir/struct_space/$subdir; fi
-    flirt -in $tempdir/$subdir/$param -applyxfm -init $tempdir/asl2struct.mat -ref $struc -out $outdir/struct_space/$subdir/$parname
+    flirt -in $tempdir/$subdir/$param -applyxfm -init $tempdir/asl2struct.mat -ref $tempdir/struc -out $outdir/struct_space/$subdir/$parname
 fi
 if [ ! -z $stdout ]; then
     if [ ! -d  $outdir/std_space/$subdir ]; then mkdir $outdir/std_space/$subdir; fi
@@ -576,6 +576,7 @@ asl_calib=${FSLDIR}/bin/asl_calib
 
 # defaults that (boolean) command line options can overide
 spatial=1; # we always use spatial priors, use --spatial=off to turn off.
+finalreg=1; # we always try to refine the registration using the perfusion image (Registration 2)
 
 # parse command line here
 until [ -z $1 ]; do
@@ -609,9 +610,11 @@ takeargs=0;boolarg="";isbool="";
 	    takeargs=1;;
 	--sbrain) strucbet=$argument # user supplied BETed structural
 		  takeargs=1;;
-	--fslanat) fslanat=$argument # user supplied fslanat dir (overrides the structural image inputs)
+	--fslanat) strucflag=1;
+		   fslanat=$argument # user supplied fslanat dir (overrides the structural image inputs)
 		   takeargs=1;;
-	--fastsrc) fastsrc=$argument # user supplied FAST results (this is the stub of the filenames)
+	--fastsrc) strucflag=1;
+		   fastsrc=$argument # user supplied FAST results (this is the stub of the filenames)
 		   takeargs=1;;
 	-r) lowstrucflag=1 lowstruc=$argument #low resolution structural image
 	    takeargs=1;;
@@ -672,7 +675,10 @@ takeargs=0;boolarg="";isbool="";
 	--t2bl) t2bl=$argument #custom T2 of blood
 	    takeargs=1;;
 	--regfrom) regfromflag=1 regfrom=$argument
-	    takeargs=1;;
+		   takeargs=1;;
+	--finalreg) isbool=1; # To turn off the final registration step that uses the perfusion image itself (with BBR) - helpful is the perfusion image is poor and thus not a good basis for registration
+		    boolarg=finalreg;
+		    ;;
 	--asl2struc) asl2struc=$argument
 	    takeargs=1;;
 	--cgain) cgain=$argument
@@ -831,17 +837,6 @@ else
 fi
 Log "Input file: $infile"
 
-if [ ! -z $strucflag ]; then
-    if [ ! -z $struc ]; then
-	if [ `${FSLDIR}/bin/imtest $struc` -eq 0 ]; then
-	    echo "ERROR: $struc is not an image/has not been found"
-	    exit 1
-	fi
-    fi
-    Log "Structural image: $struc"
-fi
-
-
 if [ ! -z $transflag ]; then
     if [ ! -e $trans ]; then
 	echo "ERROR: $trans is not a file/has not been found"
@@ -891,18 +886,23 @@ echo "Pre-processing"
 if [ ! -z $fslanat ]; then
     # we are being supplied with an fslanat directory
     # copy over the structural and brain extracted strucutral so that we can use them
-    ${FSLDIR}/bin/imcp $fslanat/T1biascorr $tempdir/struc
+    ${FSLDIR}/bin/imcp $fslanat/T1_biascorr $tempdir/struc
     ${FSLDIR}/bin/imcp $fslanat/T1_biascorr_brain $tempdir/struc_bet
     
 elif [ ! -z $struc ]; then
-    ${FSLDIR}/bin/fslmaths $struc $tempdir/struc
-    Log "Structural image is: $struc"
-    if [ -z $strucbet ]; then
-       #bet the structural for calibration and registration
-	bet $struc $tempdir/struc_bet
-	Log "BET on structural image"
+    if [ `${FSLDIR}/bin/imtest $struc` -eq 0 ]; then
+	echo "ERROR: $struc is not an image/has not been found"
+	exit 1
     else
-	${FSLDIR}/bin/fslmaths $strucbet $tempdir/struc_bet
+	${FSLDIR}/bin/fslmaths $struc $tempdir/struc
+	Log "Structural image is: $struc"
+	if [ -z $strucbet ]; then
+	    #bet the structural for calibration and registration
+	    bet $struc $tempdir/struc_bet
+	    Log "BET on structural image"
+	else
+	    ${FSLDIR}/bin/fslmaths $strucbet $tempdir/struc_bet
+	fi
     fi
 fi
 
@@ -952,13 +952,13 @@ else
     # NOT enabled at the moment - since this is only specifically useful for extensing the calibration options - TODO 
     #asl_file --data=$infile --ntis=$count --ibf=$ibf --iaf=$iaf --obf=tis --split --out=$tempdir/asldata --mean=$tempdir/asldata_mean
 
-    if [ -z $regfrom ]; then
-	# take mean over all volumes as an option to use for (initial) registration and masking
-	${FSLDIR}/bin/fslmaths $infile -Tmean $tempdir/asldata_mean
-	# brain extract this
-	${FSLDIR}/bin/bet $tempdir/asldata_mean $tempdir/asldata_mean_brain -f 0.2
-	regfrom=$tempdir/asldata_mean_brain
-    fi
+#    if [ -z $regfrom ]; then
+#	# take mean over all volumes as an option to use for (initial) registration and masking
+#	${FSLDIR}/bin/fslmaths $infile -Tmean $tempdir/asldata_mean
+#	# brain extract this
+#	${FSLDIR}/bin/bet $tempdir/asldata_mean $tempdir/asldata_mean_brain -f 0.2
+#	regfrom=$tempdir/asldata_mean_brain
+#    fi
 fi
 ### End of : Label-control subtraction
 
@@ -1377,11 +1377,13 @@ Dobasil $datafile $tempdir $initbasil
 ### Registration (2/2)
 # Revisit the registration now that we have a pefusion image (with good GM/WM contrast) using BBR
 # use existing registration for initial aligment
-if [ $register -eq 1 ]; then 
-    echo "Performing final registration"
-    Log "Final registration"
-    cp $tempdir/asl2struct.mat $outdir/native_space/asl2struct_init.mat #preserve the intial registration for future reference
-    Registration $tempdir/ftiss "-m $tempdir/mask --tissseg $tempdir/tissseg --imat $tempdir/asl2struct.mat --finalonly"
+if [ $register -eq 1 ]; then
+    if [ ! -z $finalreg ]; then
+	echo "Performing final registration"
+	Log "Final registration"
+	cp $tempdir/asl2struct.mat $outdir/native_space/asl2struct_init.mat #preserve the intial registration for future reference
+	Registration $tempdir/ftiss "-m $tempdir/mask --tissseg $tempdir/tissseg --imat $tempdir/asl2struct.mat --finalonly"
+    fi
 fi
 ### End of: Registration (2/2)
 
@@ -1468,7 +1470,7 @@ if [ ! -z $calib ]; then
     # Single M0 value for calibration
     if [ $cmethod = 'single' ]; then
 	Log "Calibration is using a single M0 value with a CSF reference"
-	if [ -z $csf ] && [ -z $struc ]; then
+	if [ -z $csf ] && [ -z $fasthasrun ]; then
 	    echo "ERROR: Provide either a structural image or CSF mask for calibration when using --cmethod=single"
 	    exit 1
 	fi
